# Generated by Django 4.2.5 on 2023-12-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('img', models.TextField()),
            ],
            options={
                'verbose_name': 'Лекарства',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='Desc',
        ),
    ]
