# Generated by Django 4.2.5 on 2023-12-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drug_rename_task_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='URL',
            field=models.CharField(default='', max_length=25),
        ),
    ]
